// Auto-generated by build.py -- do not edit directly.
// Edit the .md files in content/ and run: python3 build.py

var heroContent = {
  "badge": "",
  "name": "Uri Kogan",
  "subtitle": "Product leader who builds to discover",
  "explainer": "",
  "diffLines": [
    {
      "type": "removed",
      "text": "Old way: Define requirements, hand to engineering, wait"
    },
    {
      "type": "added",
      "text": "New way: Build working software -> real customer evidence -> proven requirements"
    },
    {
      "type": "context",
      "text": ""
    },
    {
      "type": "added",
      "text": "Built for facilities engineers, sold to CFOs, led marketers, managed suppliers, transformed organizations. I understand buyer behavior across many contexts, because I've lived in them."
    },
    {
      "type": "added",
      "text": "Consulting, product marketing, marketing leadership, product management. Operating range to think about where the industry is going, where the customer is headed, where they are now, and build the software that gets them there."
    },
    {
      "type": "added",
      "text": "Building quickly is how you discover a great product, if you have taste. Mine comes from serving enough different buyers to know what actually gets adopted."
    },
    {
      "type": "context",
      "text": ""
    }
  ],
  "stats": [
    {
      "value": "4",
      "label": "Zero-to-one products"
    },
    {
      "value": "2",
      "label": "Successful exits"
    },
    {
      "value": "15+",
      "label": "Years product leadership"
    },
    {
      "value": "5",
      "label": "VP+ roles"
    }
  ]
};

var howIWorkFiles = {
  "skill": {
    "content": [
      "# How I Work",
      "",
      "Product management is about three things: a product customers love,",
      "that your team can deliver, that makes your company successful.",
      "AI has given us a powerful new tool, but the job hasn't changed.",
      "",
      "## Patterns",
      "",
      "Practices I've found most effective across 15+ years of product leadership:",
      "",
      "- **Customer Intimacy** -- Ongoing customer relationships, not one-time",
      "  research phases. Decades of B2B GTM across every side of the table.",
      "  [references/customer-intimacy.md](customer-intimacy)",
      "",
      "- **Cross-Functional Leadership** -- Do whatever the business needs.",
      "  Fill gaps. Remove blockers. Translate between worlds.",
      "  [references/cross-functional-leadership.md](cross-functional-leadership)",
      "",
      "- **Build to Discover** -- Build working software before committing",
      "  engineering time. Working software surfaces what planning never could.",
      "  [references/build-to-discover.md](build-to-discover)",
      "",
      "- **From Business Strategy to Shipping Code** -- Analyze the market",
      "  AND build the product. No handoff required.",
      "  [references/strategy-to-shipping-code.md](strategy-to-shipping-code)",
      "",
      "- **Engineering Collaboration** -- PM builds customer evidence that",
      "  de-risks engineering investment.",
      "  [references/engineering-collaboration.md](engineering-collaboration)",
      "",
      "- **Trust as the Product** -- If the user doesn't trust the system,",
      "  the system doesn't matter.",
      "  [references/trust-as-the-product.md](trust-as-the-product)",
      "",
      "## Antipatterns",
      "",
      "Mistakes I've made and what they taught me:",
      "",
      "- **The MVP Trap** -- Built a data dashboard as the \"logical first",
      "  step.\" It was neither easy nor useful.",
      "  [references/antipattern-mvp-trap.md](antipattern-mvp-trap)"
    ]
  },
  "customer-intimacy": {
    "content": [
      "# Customer Intimacy",
      "",
      "## The Approach",
      "",
      "Build, ship, observe, expand. Customer understanding isn't something you",
      "do once and move on from -- it compounds over time as you build tools,",
      "watch how they're used, and expand what you learn into the next iteration.",
      "",
      "## Why GTM Background Matters",
      "",
      "I've spent decades on every side of the B2B table:",
      "",
      "- Selling to **CFOs** evaluating ROI models",
      "- Building tools for **facilities engineers** with clipboards and five",
      "  blinking monitors",
      "- Working with **AP clerks** processing invoices",
      "- Supporting **marketers** managing creative supply chains",
      "- Advising **commercial real estate** portfolio managers",
      "",
      "15+ persona types across 20 years. That GTM background means",
      "understanding not just what users need, but how buyers evaluate,",
      "how sellers sell, how deals close.",
      "",
      "## Evidence",
      "",
      "The vendor timing errors at a premier children's hospital and the",
      "24/7 HVAC waste at a top tech company HQ -- these weren't discovered",
      "through surveys or interviews. They were discovered by building tools",
      "and looking at real data alongside customers who trusted us enough to",
      "give us access."
    ]
  },
  "cross-functional-leadership": {
    "content": [
      "# Cross-Functional Leadership",
      "",
      "## In Practice (2025)",
      "",
      "A single quarter at R-Zero:",
      "",
      "- Became the **ODCV domain expert** when no one else would step up",
      "- Led **marketing through a leadership vacuum** while simultaneously",
      "  shipping PM deliverables",
      "- Built **customer-facing tools** when engineering was focused on",
      "  infrastructure and data pipelines",
      "- Took the company's **most important strategic initiative** from",
      "  theory to deployment to proof of value",
      "",
      "CEO strategy sessions, sales enablement tools, engineering handoffs",
      "with proven requirements -- all in the same quarter.",
      "",
      "## The Principle",
      "",
      "Product management isn't a lane. It's a commitment to making the",
      "product and the business successful by whatever means necessary.",
      "Sometimes that means writing a PRD. Sometimes it means building a",
      "prototype. Sometimes it means running marketing while the team finds",
      "a new CMO."
    ]
  },
  "build-to-discover": {
    "content": [
      "# Build to Discover",
      "",
      "## The Method",
      "",
      "Agentic engineering: validate hypotheses with working tools, not",
      "throwaway prototypes. Tools that serve real pilot customers and",
      "generate real evidence.",
      "",
      "## Discovery: Premier Children's Hospital",
      "",
      "Built a data validation tool expecting to find missing occupancy",
      "data. Instead, discovered the vendor's incorrect SOO implementation",
      "-- timing delays (15min occupied-to-standby, 5min standby-to-occupied)",
      "were completely missing. 10-15% energy savings left on the table.",
      "Customer trust shifted from their MSI to us.",
      "",
      "## Discovery: Top Tech Company HQ",
      "",
      "Built a commissioning dashboard scoped to operating hours. Expanded",
      "the data aperture and discovered nights/weekends systems running as",
      "if occupied 24/7. A configuration error bleeding money invisibly.",
      "A bigger opportunity than the original scope.",
      "",
      "## Why This Matters",
      "",
      "Both discoveries happened because working software was in front of",
      "real data. No spec, wireframe, or interview would have surfaced",
      "these -- the gap between assumption and reality only becomes visible",
      "when you build."
    ]
  },
  "strategy-to-shipping-code": {
    "content": [
      "# From Business Strategy to Shipping Code",
      "",
      "## Zooming Out",
      "",
      "Competitive positioning at the business model level. Where are",
      "incumbents structurally constrained? Build strategy around what",
      "they *can't* do -- not what they *haven't* done.",
      "",
      "Example: every major BMS vendor claims to build \"the intelligence",
      "layer for buildings.\" But their business models prevent neutrality",
      "-- Honeywell will never tell a customer to replace Honeywell",
      "equipment. The opportunity is vendor-neutral intelligence on",
      "existing infrastructure.",
      "",
      "## Zooming In",
      "",
      "Working software, customer-specific data discoveries, architecture",
      "driven by the customer's reality -- not a template.",
      "",
      "Same PM, same domain, same \"HVAC data validation\" goal -- but",
      "radically different architectures at the children's hospital",
      "(homogeneous zones: same rule applied across 100+ VAVs) versus",
      "the tech company HQ (heterogeneous equipment: 103 different metrics",
      "needing different validation logic). The customer's data model",
      "drives the architecture, not a reusable framework."
    ]
  },
  "engineering-collaboration": {
    "content": [
      "# Engineering Collaboration",
      "",
      "## The Model",
      "",
      "Engineering does foundational work -- data pipelines, infrastructure,",
      "tech debt. PM builds 0-1 customer-facing tools that serve real pilots.",
      "Those tools generate evidence: what customers actually need, which",
      "features matter, where the data model is wrong. Then engineering",
      "builds the \"engineered solution\" with high-confidence, data-backed",
      "requirements.",
      "",
      "## The Toolset Lesson",
      "",
      "Early experiments: I let Claude choose languages. It wrote Python.",
      "Built charts with Plotly. The engineering team uses React. They",
      "couldn't easily read what I'd built.",
      "",
      "The fix: configure your AI tools with the team's stack. Impose their",
      "language, their libraries, their structures. The more your output",
      "looks like what engineering already works with, the more useful it",
      "is to them.",
      "",
      "## The Result",
      "",
      "Prototypes become proven requirements. Engineering doesn't build on",
      "speculation -- they build on evidence from tools that already serve",
      "real customers."
    ]
  },
  "trust-as-the-product": {
    "content": [
      "# Trust as the Product",
      "",
      "## Three Principles",
      "",
      "### 1. Don't collect what you don't need",
      "",
      "*Retirement Advisor* -- PII stripping as trust design, not just",
      "security. What matters is the context of someone's financial",
      "situation, not their identity. Especially for older users wary of",
      "uploading private information to a website. Strip what's unnecessary,",
      "earn trust.",
      "",
      "### 2. Verify AI output systematically",
      "",
      "*Competition Bot* -- Source verification: agents check facts against",
      "original sources. Eval system: systematic testing of chatbot answers",
      "against known-good responses. Scope enforcement: discovered the agent",
      "was answering questions beyond its knowledge base, tightened",
      "instructions. The instinct to constrain AI to be reliably useful",
      "rather than impressively wrong.",
      "",
      "### 3. Keep humans in control",
      "",
      "*ODCV* -- Not making AI recommendations. Implementing customer-approved",
      "sequences based on recognized national and international standards.",
      "The customer is always in control. They approve what we do in advance.",
      "Kill switch always available. AI informs, humans decide.",
      "",
      "## The Common Thread",
      "",
      "Whether it's a senior citizen managing retirement finances, a sales",
      "rep using competitive intelligence, or a facility manager controlling",
      "HVAC -- if the user doesn't trust the system, the system doesn't",
      "matter. Trust isn't a feature. It's the product."
    ]
  },
  "antipattern-mvp-trap": {
    "content": [
      "# The MVP Trap",
      "",
      "## What Happened",
      "",
      "Built an IAQ data dashboard as the \"logical first step\" toward",
      "delivering insights. We already knew from customers and sales that",
      "insights were the endgame. The mistake: assuming raw telemetry was",
      "the natural first milestone.",
      "",
      "## Why It Failed",
      "",
      "Customers don't want minute-by-minute VOC readings on the 14th",
      "floor. They want to know: \"Is my building comfortable? Where are",
      "the problem spots? If I'm getting complaints, are they warranted?\"",
      "",
      "The dashboard was neither easy (substantial engineering work to",
      "build) nor useful (customers didn't engage with it).",
      "",
      "## The Right MVP",
      "",
      "The simplest useful insight. Not raw telemetry. Not a replica of",
      "what the hardware vendor already provides. The one piece of",
      "actionable information that proves the concept is worth pursuing.",
      "",
      "## The Painful Part",
      "",
      "My head of product was a Cagan-school disciple who preached exactly",
      "this -- validate before you build, know your customer, make sure",
      "every bet is high-conviction. We both knew the principle. We fell",
      "into the trap anyway.",
      "",
      "## The Lesson",
      "",
      "Every yes has to be high-conviction. Knowing the principle isn't",
      "enough -- you have to *feel* the cost of violating it. This failure",
      "is useful because it hurts to recall. It makes every subsequent",
      "product decision more careful."
    ]
  }
};

var projectsContent = [
  {
    "id": "project-stanford",
    "filename": "childrens-hospital.md",
    "tier": "featured",
    "title": "Premier West Coast Children's Hospital -- ODCV Data Validation",
    "body": "Narrow validation at scale: the same occupancy compliance rule applied across 100+ VAV zones. Built automated Slack reports, HTML timeline viewer, and the core savings calculation engine. TimescaleDB for time-series data handling.\n\n**Architecture driven by data model:** The hospital's zones were homogeneous -- same rule applied 100 times. This meant a narrow, deep validation engine that could catch deviations reliably at scale.",
    "before": "Expected missing data. Assumed the programmed sequence of operations (a very simple timing rule) was implemented correctly by the controls vendor. Trusted that the MSI had done their job.",
    "after": "Data was rarely missing. But the SOO was implemented incorrectly. Vendor completely missed the timing delays (15 min occupied to standby, 5 min standby to occupied). Savings being left on the table. Customer trust shifted from their MSI to us.",
    "outcome": "23-30% energy savings demonstrated. Led to a public case study. Expansion discussions now underway across the children's, adult, medical school, and university campuses. Internal reaction to the dashboard: \"THIS IS FUCKING AWESOME.\""
  },
  {
    "id": "project-qualcomm",
    "filename": "tech-campus-hq.md",
    "tier": "featured",
    "title": "Top Tech Company HQ -- ODCV Commissioning & M&V",
    "body": "Comprehensive validation of complexity: 103 heterogeneous BACnet metrics across 7 groups, 3 independent detectors (flatlining, gap, range), composite health scoring system, configurable thresholds per metric type.\n\n**Architecture driven by data model:** The campus equipment was heterogeneous -- 103 different metrics needing completely different validation logic. This meant a wide, configurable detection engine with per-metric-type thresholds and composite scoring.",
    "before": "Built initially to validate only operating hours when ODCV was active. Assumed off-hours were not relevant. BMS was delivering 17,700 CFM continuously -- over 3x the ASHRAE 62.1 code requirement at full design occupancy.",
    "after": "Expanded data aperture after seeing odd pre-hours behavior. Discovered nights and weekends systems running as if occupied 24/7. 90% OA reduction achieved (96% on weekends). A configuration error that had been bleeding money invisibly.",
    "outcome": "27% building-level energy reduction. 4.58 metric tons CO2 avoided. Zero comfort complaints. Customer now considering expansion across their entire campus and other campuses worldwide. Same PM, same domain, radically different architecture than the hospital -- because the data model demanded it."
  },
  {
    "id": "project-competition",
    "filename": "competition-bot.md",
    "tier": "medium",
    "title": "Multi-agent competitive intelligence platform",
    "body": "Built rich competitive profiles, battlecards, and comparison matrices. Shared with sales. Their biggest feedback: \"How can I use this to respond to a prospect on a call?\" Built a chatbot on the validated knowledge corpus covering dozens of competitors.\n\n**Sequence mattered:** If the chatbot came first, the knowledge corpus and data validation system wouldn't exist. Built an eval system to ensure the chatbot was generating good answers. Discovered the agent was sometimes answering with information beyond its scope -- tightened instructions to enforce boundaries.",
    "before": "",
    "after": "",
    "outcome": "CEO Alex called it \"great potential to accelerate our strategic and GTM efforts.\""
  },
  {
    "id": "project-gonggpt",
    "filename": "gonggpt.md",
    "tier": "medium",
    "title": "Voice-of-customer intelligence pipeline",
    "body": "Originally built for Product to systematically understand customer objections and feature requests from sales calls. 5-stage ETL: ingestion, speaker classification, transcript enrichment, insight extraction, structured output. 11 configuration sheet types for customizable analysis.\n\n**Cross-functional adoption:** Marketing adopted it as a key input for ABM content generation -- turning real customer objections expressed on calls into targeted content addressing those exact concerns. Became critical infrastructure for understanding VOC across the organization.",
    "before": "",
    "after": "",
    "outcome": "Product insight + marketing content from the same pipeline. VOC at scale."
  },
  {
    "id": "project-claude-workflows",
    "filename": "claude-workflows.md",
    "tier": "compact",
    "link": "https://github.com/ukogan/claude-workflows-app",
    "title": "Claude Workflows",
    "body": "Pre-dated Anthropic's CoWork. React + Hono + TypeScript. Permission dialogs with risk stratification, sandboxed execution. Evidence of product sense: saw the same opportunity as Anthropic's product team.",
    "before": "",
    "after": "",
    "outcome": ""
  },
  {
    "id": "project-ui-annotator",
    "filename": "ui-annotator.md",
    "tier": "compact",
    "link": "https://github.com/ukogan/ui-annotator",
    "title": "UI Annotator",
    "body": "Bookmarklet that injects a visual annotation overlay onto any webpage for giving structured UI feedback to AI coding agents. Point, click, annotate -- outputs JSON that Claude Code can act on directly.",
    "before": "",
    "after": "",
    "outcome": ""
  },
  {
    "id": "project-claudechatsearch",
    "filename": "claudechatsearch.md",
    "tier": "compact",
    "link": "https://github.com/ukogan/claudechatsearch",
    "title": "Claude Chat Search",
    "body": "Lightweight webapp to search through Claude Code conversation history. Full-text search across sessions with context preview. Built because Anthropic doesn't ship one yet.",
    "before": "",
    "after": "",
    "outcome": ""
  },
  {
    "id": "project-findcpa",
    "filename": "findcpa.md",
    "tier": "compact",
    "link": "https://findcpa.vercel.app",
    "title": "FindCPA",
    "body": "Integrity-first CPA matching marketplace. Guide-over-list design philosophy. Multi-Claude team workflow for development.",
    "before": "",
    "after": "",
    "outcome": ""
  }
];

var experienceContent = [
  {
    "sections": [
      {
        "label": "added",
        "items": [
          "ODCV pilot program: theory to deployment to proven value across 3 customer sites (23-30% energy savings)",
          "Pioneered agentic engineering across the company (Claude Code)",
          "AI content pipeline: customer objections to targeted blog posts (6 in 4 weeks)",
          "Passive fault detection POC achieving 95% precision",
          "Company-wide AI adoption leadership"
        ]
      },
      {
        "label": "changed",
        "items": [
          "Pivoted company from UV disinfection hardware to CRE analytics platform",
          "Led marketing through leadership vacuum while maintaining PM responsibilities",
          "Overhauled company messaging and competitive positioning"
        ]
      },
      {
        "label": "result",
        "items": [
          "10-15% energy savings recovered for pilot customers",
          "Public case study and expansion conversations"
        ]
      }
    ],
    "version": "v7.0",
    "title": "R-Zero -- VP Product & Product Marketing",
    "period": "2023 - Present"
  },
  {
    "sections": [
      {
        "label": "added",
        "items": [
          "Marketing function from scratch (Series A)",
          "$13M pipeline, $1.4M ARR YoY"
        ]
      },
      {
        "label": "result",
        "items": [
          "100% marketing-sourced pipeline"
        ]
      }
    ],
    "version": "v6.0",
    "title": "LeapFin -- VP Marketing",
    "period": "2022 - 2023"
  },
  {
    "sections": [
      {
        "label": "added",
        "items": [
          "Marketing function from scratch (seed stage)"
        ]
      },
      {
        "label": "changed",
        "items": [
          "Complete rebrand and positioning overhaul",
          "ASP increased 50% through better packaging",
          "Time to value shortened through improved implementation practices"
        ]
      },
      {
        "label": "result",
        "items": [
          "3X+ YoY ARR growth"
        ]
      }
    ],
    "version": "v5.0",
    "title": "OnPlan -- VP Marketing",
    "period": "2021 - 2022"
  },
  {
    "sections": [
      {
        "label": "fixed",
        "items": [
          "Net retention: 90% -> 125%"
        ]
      },
      {
        "label": "added",
        "items": [
          "4 product launches, new category with full GTM"
        ]
      },
      {
        "label": "changed",
        "items": [
          "Repositioned during pandemic"
        ]
      }
    ],
    "version": "v4.0",
    "title": "AppZen -- VP Product Marketing / Interim CMO",
    "period": "2019 - 2021"
  },
  {
    "sections": [
      {
        "label": "changed",
        "items": [
          "Repositioned developer product to Enterprise SaaS",
          "Created \"Product Asset Management\" category"
        ]
      },
      {
        "label": "result",
        "items": [
          "Pipeline, deal size, ARR all 3X -> 12X ARR exit"
        ]
      }
    ],
    "version": "v3.0",
    "title": "Nuxeo -- VP Product Marketing",
    "period": "2016 - 2019"
  },
  {
    "sections": [
      {
        "label": "fixed",
        "items": [
          "Returned shrinking business to growth"
        ]
      },
      {
        "label": "added",
        "items": [
          "Leads increased 5X via content marketing"
        ]
      },
      {
        "label": "changed",
        "items": [
          "Led marketing for internal startup with HP + VC-funded partners"
        ]
      }
    ],
    "version": "v2.0",
    "title": "HP -- Director Product Marketing",
    "period": "2008 - 2016"
  },
  {
    "sections": [
      {
        "label": "added",
        "items": [
          "MBA -- Kellogg School of Management",
          "BA Economics",
          "B. Music, Opera Performance"
        ]
      }
    ],
    "version": "v1.0",
    "title": "Education",
    "period": "Northwestern University"
  }
];

var testimonialsContent = [
  {
    "name": "Chris McLaughlin",
    "role": "Chief Product Officer, Nuxeo",
    "body": "Uri was instrumental in positioning the company in the Digital Asset Management space and in developing our enterprise DAM GTM strategy. He is also very adept at learning new technologies and markets and rapidly establishing himself as a thought leader."
  },
  {
    "name": "Kuldeep Misri",
    "role": "Director PM, Salesforce",
    "body": "Uri is one of the best leaders I've worked with. He's an execution machine. He singlehandedly relaunched our product... Despite being new to our market, he became an expert and compelling spokesperson within a few months."
  },
  {
    "name": "Caitlin Steel",
    "role": "M2 Product, Leapfin",
    "body": "Uri was a key collaborator when I led product at Leapfin, helping sharpen my thinking about the product vision and roadmap. I have worked with him extensively since then as a coach and thought partner to problem solve product strategy, internal alignment, and management challenges. He brings clarity and originality to every conversation and connects the dots in ways I've never seen."
  },
  {
    "name": "Wendy Yale",
    "role": "CMO, AppZen",
    "body": "As interim CMO, Uri lay a strong foundation that helped me quickly establish myself when I joined AppZen as CMO. His transparency and clear understanding of marketing, the state of the product, and the opportunities and challenges across the business were prescient."
  },
  {
    "name": "Kash Kapadia",
    "role": "VP, HP",
    "body": "Uri was a central leader in our launch of new businesses combining software, services, and global distribution."
  },
  {
    "name": "David Greenbaum",
    "role": "CEO, OnPlan",
    "body": "Uri delivered phenomenal work. His strategic marketing, product, and Board management work was critical to our success, and his presence elevated our management team. Uri's ideas and execution helped us dramatically increase our selling price in just a few months."
  }
];

var contactContent = {
  "heading": "Available for Consulting & Advisory",
  "cta_href": "https://linkedin.com/in/kogan/",
  "cta_text": "Merge -- Connect on LinkedIn",
  "intro": "Someone doing the work who can help others do it too. I teach teams to use agentic engineering, help product and engineering collaborate as AI shifts roles, and advise on applied AI product strategy.",
  "cards": [
    {
      "title": "Agentic Engineering Coaching",
      "desc": "Teach teams to use AI tools to move faster and be more customer-centric. Not prompt engineering -- product engineering with AI as a collaborator."
    },
    {
      "title": "Eng/Product Collaboration",
      "desc": "Help engineering and product teams collaborate better as AI shifts traditional role boundaries. Who builds what, when, and why."
    },
    {
      "title": "Applied AI Product Strategy",
      "desc": "Helping companies figure out how to use AI to solve their specific business problems. Not generic \"add AI\" advice -- analysis of your competitive landscape, your customers, your constraints."
    }
  ]
};

var contributionsData = {
  "total": 413,
  "contributions": [
    {
      "date": "2025-02-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-02-24",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-02-25",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-02-26",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-02-27",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-02-28",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-01",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-03",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-05",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-06",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-07",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-08",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-09",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-10",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-11",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-12",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-13",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-15",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-16",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-17",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-18",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-19",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-20",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-21",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-22",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-24",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-25",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-26",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-27",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-28",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-29",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-30",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-03-31",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-01",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-03",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-05",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-06",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-07",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-08",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-09",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-10",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-11",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-12",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-13",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-15",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-16",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-17",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-18",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-19",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-20",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-21",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-22",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-24",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-25",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-26",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-27",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-28",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-29",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-04-30",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-01",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-03",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-05",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-06",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-07",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-08",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-09",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-10",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-11",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-12",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-13",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-15",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-16",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-17",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-18",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-19",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-20",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-21",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-22",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-24",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-25",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-26",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-27",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-28",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-29",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-30",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-05-31",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-01",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-03",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-05",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-06",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-07",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-08",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-09",
      "count": 1,
      "level": 1
    },
    {
      "date": "2025-06-10",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-11",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-12",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-13",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-15",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-16",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-17",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-18",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-19",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-20",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-21",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-22",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-24",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-25",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-26",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-27",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-28",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-29",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-06-30",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-01",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-03",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-05",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-06",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-07",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-08",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-09",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-10",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-11",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-12",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-13",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-15",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-16",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-17",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-18",
      "count": 4,
      "level": 1
    },
    {
      "date": "2025-07-19",
      "count": 1,
      "level": 1
    },
    {
      "date": "2025-07-20",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-21",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-22",
      "count": 5,
      "level": 1
    },
    {
      "date": "2025-07-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-24",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-25",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-26",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-27",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-28",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-29",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-30",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-07-31",
      "count": 1,
      "level": 1
    },
    {
      "date": "2025-08-01",
      "count": 6,
      "level": 2
    },
    {
      "date": "2025-08-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-03",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-05",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-06",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-07",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-08",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-09",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-10",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-11",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-12",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-13",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-15",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-16",
      "count": 5,
      "level": 1
    },
    {
      "date": "2025-08-17",
      "count": 14,
      "level": 3
    },
    {
      "date": "2025-08-18",
      "count": 9,
      "level": 2
    },
    {
      "date": "2025-08-19",
      "count": 8,
      "level": 2
    },
    {
      "date": "2025-08-20",
      "count": 17,
      "level": 3
    },
    {
      "date": "2025-08-21",
      "count": 18,
      "level": 4
    },
    {
      "date": "2025-08-22",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-24",
      "count": 3,
      "level": 1
    },
    {
      "date": "2025-08-25",
      "count": 7,
      "level": 2
    },
    {
      "date": "2025-08-26",
      "count": 6,
      "level": 2
    },
    {
      "date": "2025-08-27",
      "count": 10,
      "level": 2
    },
    {
      "date": "2025-08-28",
      "count": 6,
      "level": 2
    },
    {
      "date": "2025-08-29",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-30",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-08-31",
      "count": 8,
      "level": 2
    },
    {
      "date": "2025-09-01",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-03",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-05",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-06",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-07",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-08",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-09",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-10",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-11",
      "count": 33,
      "level": 4
    },
    {
      "date": "2025-09-12",
      "count": 9,
      "level": 2
    },
    {
      "date": "2025-09-13",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-15",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-16",
      "count": 8,
      "level": 2
    },
    {
      "date": "2025-09-17",
      "count": 20,
      "level": 4
    },
    {
      "date": "2025-09-18",
      "count": 5,
      "level": 1
    },
    {
      "date": "2025-09-19",
      "count": 2,
      "level": 1
    },
    {
      "date": "2025-09-20",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-21",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-22",
      "count": 15,
      "level": 3
    },
    {
      "date": "2025-09-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-24",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-25",
      "count": 12,
      "level": 3
    },
    {
      "date": "2025-09-26",
      "count": 8,
      "level": 2
    },
    {
      "date": "2025-09-27",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-28",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-09-29",
      "count": 12,
      "level": 3
    },
    {
      "date": "2025-09-30",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-01",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-03",
      "count": 10,
      "level": 2
    },
    {
      "date": "2025-10-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-05",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-06",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-07",
      "count": 33,
      "level": 4
    },
    {
      "date": "2025-10-08",
      "count": 4,
      "level": 1
    },
    {
      "date": "2025-10-09",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-10",
      "count": 10,
      "level": 2
    },
    {
      "date": "2025-10-11",
      "count": 2,
      "level": 1
    },
    {
      "date": "2025-10-12",
      "count": 23,
      "level": 4
    },
    {
      "date": "2025-10-13",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-15",
      "count": 1,
      "level": 1
    },
    {
      "date": "2025-10-16",
      "count": 9,
      "level": 2
    },
    {
      "date": "2025-10-17",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-18",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-19",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-20",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-21",
      "count": 2,
      "level": 1
    },
    {
      "date": "2025-10-22",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-24",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-25",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-26",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-27",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-28",
      "count": 3,
      "level": 1
    },
    {
      "date": "2025-10-29",
      "count": 5,
      "level": 1
    },
    {
      "date": "2025-10-30",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-10-31",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-01",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-03",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-05",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-06",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-07",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-08",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-09",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-10",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-11",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-12",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-13",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-15",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-16",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-17",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-18",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-19",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-20",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-21",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-22",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-24",
      "count": 1,
      "level": 1
    },
    {
      "date": "2025-11-25",
      "count": 1,
      "level": 1
    },
    {
      "date": "2025-11-26",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-27",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-28",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-29",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-11-30",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-01",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-03",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-05",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-06",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-07",
      "count": 3,
      "level": 1
    },
    {
      "date": "2025-12-08",
      "count": 1,
      "level": 1
    },
    {
      "date": "2025-12-09",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-10",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-11",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-12",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-13",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-15",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-16",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-17",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-18",
      "count": 3,
      "level": 1
    },
    {
      "date": "2025-12-19",
      "count": 2,
      "level": 1
    },
    {
      "date": "2025-12-20",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-21",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-22",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-24",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-25",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-26",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-27",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-28",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-29",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-30",
      "count": 0,
      "level": 0
    },
    {
      "date": "2025-12-31",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-01",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-03",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-05",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-06",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-07",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-08",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-09",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-10",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-11",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-12",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-13",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-15",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-16",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-17",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-18",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-19",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-20",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-21",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-22",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-23",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-24",
      "count": 2,
      "level": 1
    },
    {
      "date": "2026-01-25",
      "count": 1,
      "level": 1
    },
    {
      "date": "2026-01-26",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-27",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-01-28",
      "count": 7,
      "level": 2
    },
    {
      "date": "2026-01-29",
      "count": 2,
      "level": 1
    },
    {
      "date": "2026-01-30",
      "count": 1,
      "level": 1
    },
    {
      "date": "2026-01-31",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-01",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-02",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-03",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-04",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-05",
      "count": 2,
      "level": 1
    },
    {
      "date": "2026-02-06",
      "count": 8,
      "level": 2
    },
    {
      "date": "2026-02-07",
      "count": 6,
      "level": 2
    },
    {
      "date": "2026-02-08",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-09",
      "count": 5,
      "level": 1
    },
    {
      "date": "2026-02-10",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-11",
      "count": 1,
      "level": 1
    },
    {
      "date": "2026-02-12",
      "count": 2,
      "level": 1
    },
    {
      "date": "2026-02-13",
      "count": 1,
      "level": 1
    },
    {
      "date": "2026-02-14",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-15",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-16",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-17",
      "count": 4,
      "level": 1
    },
    {
      "date": "2026-02-18",
      "count": 3,
      "level": 1
    },
    {
      "date": "2026-02-19",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-20",
      "count": 0,
      "level": 0
    },
    {
      "date": "2026-02-21",
      "count": 2,
      "level": 1
    },
    {
      "date": "2026-02-22",
      "count": 0,
      "level": 0
    }
  ]
};
